# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
branches:
include:
- main
pool:
vmImage: 'ubuntu-latest'
steps:
- task: Docker@2
inputs:
command: 'buildAndPush'
repository: 'tmwacr.azurecr.io/azure-vote'
dockerfile: 'Dockerfile'
containerRegistry: 'tmwacr'
tags: 'v$(Build.BuildId)'